target "DistributedFlow" do
  pod 'ANDistributedFlowLayout', :path => '..'
  pod 'KTCategories', git: 'https://github.com/keighl/KTCategories.git'
end

target "DistributedFlowTests" do
  pod 'ANDistributedFlowLayout', :path => '..'
  pod 'KTCategories', git: 'https://github.com/keighl/KTCategories.git'
end

